### ISSUE TITLE
srs: use case diagram

### ISSUE THREAD

**Issue by crystalcheong** [mawsters/docs#4]
- [x] baseline use case diagrams
  - [x] use case descriptions
- [x] functional & non-functional requirements in srs

**Comment by yuhaopro** [comment]
- Do our Exception and Alternative Flows need to follow the use case description template, or should we use our own formatting?
Example: 5.3 in Alternative Flow would suggest use case 5, and Alternative flow number 3. There is no indication of where this alternative flow occurs.
Example: “5.0.E.2” in Exceptio would indicate the second exception for the normal flow for use case number 5. This also does not indicate which part of the normal flow does the exception occur.

- Should the use case for "Change Password" Be an optional use case to the diagram?

**Comment by yuhaopro** [comment]
Tip: For each lab session, only flesh out the pages that are done in the SRS. Selectively remove the parts filled with placeholders.

**Comment by crystalcheong** [comment]
merged https://github.com/mawsters/docs/commit/7e90ea087c2268dc4e1558a39c69d260333092cb
